X = input("Digite algo: ")
print("O tipo da sua mensagem é", type(X))
print("Sua mensagem tem apenas espaços? ", X.isspace())
print("Sua mensagem é apenas numeros?", X.isnumeric())
print("Sua mensagem é alfabetica?", X.isalpha())
print("Sua mensagem é alfanumerica?", X.isalnum())
print("Sua mensagem esta em maiusculo?", X.isupper())
print("Sua mensagem esta em minusculo?", X.islower())
print("Sua mensagem é maiuscula com minuscula?", X.istitle())
